// <auto-generated />
namespace TwentyFourHourProject.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class NewMigrationAt1132pm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewMigrationAt1132pm));
        
        string IMigrationMetadata.Id
        {
            get { return "202102060432200_NewMigrationAt1132pm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
